routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/duas/trash', 'DuaController@trash')->name('duas.trash');
Route::get('/duas/trash/{id}/restore', 'DuaController@restore')->name('duas.restore');
Route::get('/duas/trash/{id}/permanent_delete', 'DuaController@permanentDelete')->name('duas.permanent_delete');


// duas route
Route::resource('duas', 'DuaController');

// admin routes


Route::get('/admin/duas', 'AdminController@duas');

app/Dua.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Dua extends Model
{

  
    use SoftDeletes;
    protected $fillable = ['status','title','arabic','translation','transliteration','reference'];

    protected $dates = ['deleted_at'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use App\Dua;
use Illuminate\Http\Request;

class AdminController extends Controller
{
    public function duas(){
        $publishedDuas = Dua::where('status', 1)->get();
        $trashedDuas = Dua::where('status', 0)->get();

        return view('admin.duas', compact('publishedDuas', 'trashedDuas'));
    }
}

app/Http/Controllers/ApiController.php
<?php

namespace App\Http\Controllers;

use App\Dua;
use Illuminate\Http\Request;

class ApiController extends Controller
{
    public function getAllDua(){
        $allDua = Dua::all();

        return $allDua;
    }


    public function getOneDua(Dua $dua){

       $dua  = Dua::findOrFail($dua);

       return $dua;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DuaController.php
<?php

namespace App\Http\Controllers;

use App\Dua;
use Illuminate\Http\Request;

class DuaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $duas = Dua::where('status', 1)->get();

       return view('duas.index', compact('duas'));

       
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('duas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $dua = new Dua();
        $dua->title = $request->title;
        $dua->arabic = $request->arabic;
        $dua->translation = $request->translation;
        $dua->transliteration = $request->transliteration;
        $dua->reference = $request->reference;
        
        
        $dua->save();

        return redirect('duas');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Dua  $dua
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $dua = Dua::findOrFail($id);
        return view('duas.show',compact('dua'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Dua  $dua
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dua = Dua::findOrFail($id);

        return view('duas.edit',compact('dua')); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Dua  $dua
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $input = $request->all();
        $dua = Dua::findOrFail($id);
        // $dua->status = $request->status;
        // $dua->title = $request->title;
        // $dua->arabic = $request->arabic;
        // $dua->translation = $request->translation;
        // $dua->transliteration = $request->transliteration;
        // $dua->reference = $request->reference;
        $dua->update($input);

        return redirect('duas');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Dua  $dua
     * @return \Illuminate\Http\Response
     */
    // public function destroy($id)
    // {
    //     $dua = Dua::findOrFail($id);

    //     $dua->delete();

    //     return redirect('duas');
    // }



    // trashed duas 

    public function destroy($id){

        $dua = Dua::findOrFail($id);

        $dua->delete();

        return redirect('duas');
    }



    public function trash(){

        $trashedDuas = Dua::onlyTrashed()->get();

        return view('duas.trash',compact('trashedDuas'));
    }

    public function restore($id){

        $duasRestore = Dua::onlyTrashed()->findOrFail($id);

        $duasRestore->restore($duasRestore);

        return redirect('duas');
    }

    public function permanentDelete($id){

        $permanetDelete = Dua::onlyTrashed()->findOrFail($id);

        $permanetDelete->forceDelete($permanetDelete);

        return redirect('duas');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/admin/duas.blade.php
@extends('layouts.app')


@section('content')

<div class="container">
    <h3 class="text-center pb-5">Manage Duas</h3>
    <div class="row pt-5">

        <div class="col-md-6">
             <h3>Published</h3>
             <hr>
             <div class="pt-4">
             @foreach ($publishedDuas as $dua)
             <h2> <a href=" {{route("duas.show", $dua->id)}} ">{{$dua->title}}</a> </h2>


             <form action= " {{route('duas.update', $dua->id)}} " method="post"> 

                {{ method_field('patch')}}

                @csrf

                <input type="hidden" name="status" value="0">
                <button type="submit" class="btn btn-success btn-sm">Save as Draft</button>
            </form>

             @endforeach
             </div>
        </div>

        <div class="col-md-6">
            <h3>Unpublished</h3>
            <hr>
            <div class="pt-4">
            @foreach ($trashedDuas as $dua)
            <h2> <a href=" {{route("duas.show", $dua->id)}} ">{{$dua->title}}</a> </h2>
        


            <form action= " {{route('duas.update', $dua->id)}} " method="post"> 

                {{ method_field('patch')}}
                   
                    @csrf
    
                    <input type="hidden" name="status" value="1">
                    <button type="submit" class="btn btn-success btn-sm">Save as Published</button>
                </form>
            @endforeach

            </div>
        </div>
    </div>
</div>

@endsection

resources/views/duas/create.blade.php
@extends('layouts.app')

@section('content')


 <div class="container">
    
         <h1 class="display-3">Create New Dua </h1>
  

     <div class="col-md-12">
         <form action= " {{route('duas.store')}} " method="post" enctype="multipart/form-data"> 
            @csrf
             <div class="form-group">
                 <label for="title">Title</label>
                 <textarea name="title" id="" cols="30" rows="4" class="form-control"></textarea>
             </div>
             <div class="form-group">
                <label for="arabic">Arabic</label>
               <textarea name="arabic" id="" cols="30" rows="6" class="form-control"></textarea>
            </div>
            <div class="form-group">
                <label for="translation">Translation</label>
               <textarea name="translation" id="" cols="30" rows="6" class="form-control"></textarea>
            </div>

            <div class="form-group">
                <label for="transliteration">Transliteration</label>
               <textarea name="transliteration" id="" cols="30" rows="6" class="form-control"></textarea>
            </div>

            <div class="form-group">
                <label for="reference">Reference</label>
               <textarea name="reference" id="" cols="30" rows="4" class="form-control"></textarea>
            </div>

        
            <div>
                <button type="submit" class="btn btn-success">Create Dua</button>
            </div>
           
         </form>
     </div>


 </div>

@endsection

resources/views/duas/edit.blade.php
@extends('layouts.app')

@section('content')


 <div class="container pb-5">
    
         <h1 class="display-3">Edit Dua </h1>
  

     <div class="col-md-12">
         <form action= " {{route('duas.update', $dua->id)}} " method="post"> 

            {{ method_field('patch')}}
            @csrf
             <div class="form-group">
                 <label for="title">Title</label>
                 <textarea name="title" id="" cols="30" rows="4" class="form-control"> {{$dua->title}} </textarea>
             </div>
             <div class="form-group">
                <label for="arabic">Arabic</label>
               <textarea name="arabic" id="" cols="30" rows="6" class="form-control"> {{$dua->arabic}} </textarea>
            </div>
            <div class="form-group">
                <label for="translation">Translation</label>
               <textarea name="translation" id="" cols="30" rows="6" class="form-control"> {{$dua->translation}} </textarea>
            </div>

            <div class="form-group">
                <label for="transliteration">Transliteration</label>
               <textarea name="transliteration" id="" cols="30" rows="6" class="form-control"> {{$dua->transliteration}} </textarea>
            </div>

            <div class="form-group">
                <label for="reference">Reference</label>
               <textarea name="reference" id="" cols="30" rows="4" class="form-control"> {{$dua->reference}} </textarea>
            </div>

            <div class="form-group">
               <label for="status">Status</label>
               <select class="form-control" name="status">
                <option value="1" >Active</option>
                <option value="0">Inactive</option>
                
              </select>
            </div>

        
            <div>
                <button type="submit" class="btn btn-success float-left">Edit Dua</button>
            </div>
           
         </form>


         <form action=" {{route('duas.destroy' ,$dua->id)}} " method="post">
            {{ method_field('delete') }}
            @csrf
         <button type="submit" class="btn btn-danger xs float-right">
             Delete
         </button>
        </form>
     </div>


 </div>

@endsection

resources/views/duas/index.blade.php
@extends('layouts.app')


@section('content')
    <div class="container">
        @foreach ($duas as $dua)
          <a href=" {{route('duas.show' ,$dua->id)}} ">  <h3 class="text-center"> {{$dua->title}} </h3> </a>
        @endforeach
    </div>
@endsection

resources/views/duas/show.blade.php
@extends('layouts.app')


@section('content')
<div class="container w-50 text-center">
    <h3> {{$dua->title}} </h3>

    <p> {{$dua->arabic}} </p>

    <p> {{$dua->translation}} </p>
    <p> {{$dua->transliteration}} </p>
    <blockquote class=" float-right"> {{$dua->reference}} </blockquote>

</div>
     
@endsection

resources/views/duas/trash.blade.php
@extends('layouts.app')


@section('content')


<div class="container">

    <div class="jumbotron">
        <h1>Trashed Duas</h1>
    </div>
    <div class="col-md-12">

        @foreach ($trashedDuas as $dua)

        <h2>{{$dua->title}} </h2>

     <form action=" {{route('duas.restore' ,$dua->id)}} " method="get">

        @csrf
     <button type="submit" class="btn btn-success xs ">
         Restore
     </button>
    </form>

    <form action=" {{route('duas.permanent_delete' ,$dua->id)}} " method="delete">

        @csrf
     <button type="submit" class="btn btn-danger xs float-right">
         Delete Permanently
     </button>
    </form>
    
    @endforeach
    </div>
</div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>